name: Build and Release WPF Application

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Create zip archive
      run: |
        New-Item -ItemType Directory -Path "release" -Force
    
        $version = "1.0.0"
        if ($env:GITHUB_REF -like "refs/tags/*") {
            $version = $env:GITHUB_REF -replace "refs/tags/v", ""
        }
    
        Compress-Archive -Path "./publish/*" -DestinationPath "./release/TBank_GetUserId-v$version.zip" -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TBank_GetUserId
        path: ./publish/

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/TBank_GetUserId-v*
        body: |
          Automated release of WPF application
          - Version: ${{ github.ref_name }}
          - Commit: ${{ github.sha }}
          - Built with .NET Core 3.1
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}